blog/urls.py
from django.urls import path
from .views import blog_index, blog_detail, blog_category, reply
from .feeds import LatestArticlesFeed
app_name = 'blog'

urlpatterns = [
    path('', blog_index, name='index'),
    path('<int:pk>/', blog_detail, name='detail'),
    path('<category>/', blog_category, name='category'),
    path('tag/<slug:tag_slug>/', blog_index, name='post_tag'),
    path('comment/reply/', reply, name='comment_reply'),
    path('feed/', LatestArticlesFeed(), name='article_feed'),
]

blog2/urls.py
from django.urls import path
from blog2 import views
from blog2.feeds import LatestPostsFeed

app_name = 'blog2'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('comment/reply/', views.reply_page, name='reply'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_tag'),
    path('about', views.about, name='about'),
]

djflow/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.urls import path, include
from blog2 import views
from blog2.sitemaps import PostSitemap
from blog.sitemaps import ArticleSitemap


sitemaps = {
    'posts': PostSitemap,
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('djflow/', admin.site.urls),
    path('', views.post_list, name='post_list'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('blog2/', include('blog2.urls', namespace='blog2')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Article(models.Model):
    user = models.ForeignKey(User, related_name='post',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = RichTextUploadingField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='feature_img/%Y/%m/%d', null=True)
    categories = models.ManyToManyField(Category, related_name='posts')
    tags = TaggableManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    author = models.CharField(max_length=60)
    email = models.EmailField(null=True, blank=True)
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    updated = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey(
        'self', related_name='parents', on_delete=models.CASCADE, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.post.title + ' ' + self.author

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
   
   class Meta:
       model = Comment
       fields = ('author', 'email', 'body')
       widgets = {
            'author':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nom...'}),
            'email':forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Email...'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Commentaire...'}),
       }

blog/views.py
from multiprocessing import context
from operator import ne
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from .models import Article, Category, Comment
from taggit.models import Tag
from .forms import CommentForm


def blog_index(request, tag_slug=None):
    posts = Article.objects.all().order_by('-created_on')
    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    query = request.GET.get('q')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if query:
        posts = Article.objects.filter(
            Q(title__icontains=query) | Q(categories__name__icontains=query))
    context = {
        'posts': posts,
    }
    return render(request, 'blog/blog_index.html', context)


def blog_category(request, category):
    posts = Article.objects.filter(categories__name__contains=category
                                   ).order_by('-created_on')
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, 'blog/blog_category.html', context)


def blog_detail(request, pk):
    post = Article.objects.get(pk=pk)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        form = CommentForm()
    query = request.GET.get('q')
    if query:
        post = Article.objects.filter(Q(title__icontains=query) | Q(
            body__icontains=query) | Q(categories__name__icontains=query))

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Article.objects.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by('-same_tags',)[:6]

    context = {
        'comments': comments,
        'post': post,
        'form': form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/blog_detail.html', context)


def reply(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)
            reply.post = Article(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()

            return redirect(post_url+'#'+str(reply.id))

    return redirect('/')

blog/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="{% static 'img/djicon.png' %}">
    <title>djflow-{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- highlight js -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- static file -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
</head>
    <body>

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
          <div class="container">
              <a class="navbar-brand fs-1" href="{% url 'blog2:post_list' %}">Django-<span class="logo">Flow</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog2:post_list' %}">Django</a>
                  </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/tag/tips/' %}active{% endif %}" href="{% url 'blog:index' %}">Python</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'blog2:about' %}" class="nav-link">About</a>
                </li>
              </ul> 
              <form class="d-flex">
                  <input class="form-control mr-0" type="search" placeholder="Search" aria-label="Search" value="{{ request.get.q }}" name="q">
              </form>
          </div>
          </div>
      </nav>
      <main class="container my-3">
          <h2 class="my-3">
            {% if request.GET.q is not null %}
              Search Results for "{{ request.GET.q }}"
            {% endif %}
          </h2>
            
          {% block content %}

          {% endblock %}
      </main>
      <hr />
      <footer class="container-fluid footer">
        <p class="text-center text-decoration-none pt-5">
          <a class="/" href="">Termes Et Conditions</a>|
          <a href="/">Politique de Cookies </a>|
          <a href="/">Politique de Confidentialité</a>|
          <a href="mailto:diarra.msa@gmail.com">Contact me</a>
        </p>
        <p class="text-center"><span class="averti border p-2">Ne vendez pas mes infos</span></p>
        <p class="foot pt-5 text-center">&copy; {% now "Y" %} Copyright <span>django flow</span></p>
      </footer>

    <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
        <script id="dsq-count-scr" src="//django-flow.disqus.com/count.js" async></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

blog/templates/comments.html
<div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = "http://127.0.0.1:4000/blog/{{pk}}/";  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = "{{url}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://django-flow.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>