blog/urls.py
from django.urls import path
from .views import blog_index, blog_detail, blog_category, reply
from .feeds import LatestArticlesFeed
app_name = 'blog'

urlpatterns = [
    path('', blog_index, name='index'),
    path('<int:pk>/', blog_detail, name='detail'),
    path('<category>/', blog_category, name='category'),
    path('tag/<slug:tag_slug>/', blog_index, name='post_tag'),
    path('comment/reply/', reply, name='comment_reply'),
    path('feed/', LatestArticlesFeed(), name='article_feed'),
]

djflow/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.urls import path, include
from blog2 import views
from blog2.sitemaps import PostSitemap
from blog.sitemaps import ArticleSitemap


sitemaps = {
    'posts': PostSitemap,
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('djflow/', admin.site.urls),
    path('', views.post_list, name='post_list'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('blog2/', include('blog2.urls', namespace='blog2')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Article(models.Model):
    user = models.ForeignKey(User, related_name='post',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = RichTextUploadingField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='feature_img/%Y/%m/%d', null=True)
    categories = models.ManyToManyField(Category, related_name='posts')
    tags = TaggableManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    author = models.CharField(max_length=60)
    email = models.EmailField(null=True, blank=True)
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    updated = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey(
        'self', related_name='parents', on_delete=models.CASCADE, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.post.title + ' ' + self.author

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
   
   class Meta:
       model = Comment
       fields = ('author', 'email', 'body')
       widgets = {
            'author':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nom...'}),
            'email':forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Email...'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Commentaire...'}),
       }

blog/views.py
from multiprocessing import context
from operator import ne
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from .models import Article, Category, Comment
from taggit.models import Tag
from .forms import CommentForm


def blog_index(request, tag_slug=None):
    posts = Article.objects.all().order_by('-created_on')
    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    query = request.GET.get('q')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if query:
        posts = Article.objects.filter(
            Q(title__icontains=query) | Q(categories__name__icontains=query))
    context = {
        'posts': posts,
    }
    return render(request, 'blog/blog_index.html', context)


def blog_category(request, category):
    posts = Article.objects.filter(categories__name__contains=category
                                   ).order_by('-created_on')
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, 'blog/blog_category.html', context)


def blog_detail(request, pk):
    post = Article.objects.get(pk=pk)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        form = CommentForm()
    query = request.GET.get('q')
    if query:
        post = Article.objects.filter(Q(title__icontains=query) | Q(
            body__icontains=query) | Q(categories__name__icontains=query))

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Article.objects.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by('-same_tags',)[:6]

    context = {
        'comments': comments,
        'post': post,
        'form': form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/blog_detail.html', context)


def reply(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)
            reply.post = Article(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()

            return redirect(post_url+'#'+str(reply.id))

    return redirect('/')

blog/templates/blog/blog_category.html
{% extends "base.html" %}

{% block title %}blog-category{% endblock %}

{% block content %}
<article class="container">
    <div class="col-md-12">
        <h1>{{ category | title }}</h1>
        <hr >
        {% for post in posts %}
            <h2 class="mt-4"><a href="{% url 'blog:detail' post.pk %}" class="text-decoration-none text-dark fw-bolder">{{ post.title }}</a></h2>
            <small>
                {{ post.created_on.date }} |&nbsp;
                Categories:&nbsp;
                {% for category in post.categories.all %}
                <a href="{% url 'blog:category' category.name %}" class="text-decoration-none">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
            </small>
            <p>{{ post.body |truncatewords:30|safe }}........</p>
            <div>
                <a href="{{ post.get_absolute_url }}" class="btn btn-info btn-sm p-3 text-uppercase text-white fw-bolder">Read more</a>
            </div>
        {% endfor %}
    </div>
</article>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}blog-details {% endblock %}
{% block content %}
<article class="container">
  <div class="col-md-12">
    <h1 class="fs-1 fw-bolder text-center mt-5">{{ post.title }}</h1>
    <p class="text-center">
      <small>
        by {{ post.user.username }} · {{ post.created_on.date }} | &nbsp;
        Categories:&nbsp; {% for category in post.categories.all %}
        <a
          href="{% url 'blog:category' category.name %}"
          class="text-decoration-none badge bg-primary"
        >
          {{ category.name }}
        </a>
        {% endfor %}
      </small>
    </p>
    <hr />
    <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static
    "img/no_img.png" %}{% endif %}" height="500px" width="100%">
    <p>{{ post.body|safe}}</p>
    <p>
      <strong>Tags:</strong>
      {% for tag in post.tags.all %}
      <a
        href="{% url 'blog:post_tag' tag.slug %}"
        class="link-light text-decoration-none badge bg-secondary"
      >
        {{ tag.name }}
      </a>
      {% endfor %}
    </p>
    <br />
    <hr />
    {% include 'comments.html' with url=post.pk %}
    <hr />
    <div class="my-3 fw-bolder">
      <h3>Similar Posts</h3>
    </div>
    <div class="row">
      {% for post in similar_posts %}
      <div class="col-md-6 col-sm-6 col-lg-4 mb-3">
        <div class="card border-0">
          <div class="ratio ratio-16x9">
            <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static
            "img/no_img.png" %}{% endif %}">
          </div>
          <div class="card-body p-0 m-0 mt-2">
            <h4 class="card-title mt-3 py-0">
              <a
                href="{{ post.get_absolute_url }}"
                class="text-center text-decoration-none text-dark"
                >{{ post.title }}</a
              >
            </h4>
            <p class="card-text">
              <small class="text-muted">
                <span
                  >{{post.created_on.date}} by
                  <strong>{{ post.user.username }}</strong></span
                >
                <!-- <a href="" class="badge badge-light text-muted">{{post.tags.all|join:" "}}</a> -->
              </small>
            </p>
            <!-- <p>{{post.body|truncatechars:100|linebreaks}}</p> -->
          </div>
        </div>
      </div>
      {% empty %}
      <p class="text-muted">There is no similar post yet</p>
      {% endfor %}
    </div>
  </div>
</article>
{% endblock %}

blog/templates/blog/blog_index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}blog-list{% endblock %}

{% block content %}
<article class="container">
    <div class="col-md-12">
        <h1>Python Programming Language</h1>
        <hr />
        {% if tag %}
            <h2 class="mb-3">Post tagged with "{{ tag.name }}"</h2>
        {% endif %}
        {% for post in posts %}
        <h2 class="mt-4"><a href="{% url 'blog:detail' post.pk %}" class="text-decoration-none text-dark fw-bolder">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
                <a href="{% url 'blog:category' category.name %}" class="text-decoration-none">
                    {{ category.name }}
                </a>&nbsp;
            {% endfor %}
        </small>
        <p class="mt-4">{{ post.body|truncatewords:30|safe}} ....</p>
        <div class="mt-3">
            <a href="{{ post.get_absolute_url }}" class="btn btn-info btn-sm p-3 text-uppercase text-white fw-bolder">Read more</a>
        </div>
        {% endfor %}
        {% include "blog/pagination.html" with page=posts %}
    </div>
</article>
{% endblock %}

blog/templates/blog/comment.html
<div class="border-0 border-start border-2 border-info ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>{{comment.author}}</strong> 
        {% if  comment.parent.author%} to <strong>{{comment.parent.author}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{comment.body}}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'blog:comment_reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">
                {{form.as_p}}
                <div>
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'blog/comment.html' with comment=comment %}
    {% endfor %}
</div>

blog/templates/blog/pagination.html
<nav aria-label="Page navigation example mt-4">
  <ul class="pagination justify-content-center">
    <li class="page-item">
        {% if page.has_previous %}
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    </li>
    <li class="page-item">
        <a class="page-link" href="#">{{ page.number }}</a>
    </li>

    <li class="page-item">
        {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </li>
  </ul>
</nav>