blog/urls.py
from django.urls import path
from .views import blog_index, blog_detail, blog_category, reply
from .feeds import LatestArticlesFeed
app_name = 'blog'

urlpatterns = [
    path('', blog_index, name='index'),
    path('<int:pk>/', blog_detail, name='detail'),
    path('<category>/', blog_category, name='category'),
    path('tag/<slug:tag_slug>/', blog_index, name='post_tag'),
    path('comment/reply/', reply, name='comment_reply'),
    path('feed/', LatestArticlesFeed(), name='article_feed'),
]

blog2/urls.py
from django.urls import path
from blog2 import views
from blog2.feeds import LatestPostsFeed

app_name = 'blog2'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('comment/reply/', views.reply_page, name='reply'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_tag'),
    path('about', views.about, name='about'),
]

djflow/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.urls import path, include
from blog2 import views
from blog2.sitemaps import PostSitemap
from blog.sitemaps import ArticleSitemap


sitemaps = {
    'posts': PostSitemap,
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('djflow/', admin.site.urls),
    path('', views.post_list, name='post_list'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('blog2/', include('blog2.urls', namespace='blog2')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

blog2/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

# creating models manager


class PublishedManager(models.Manager):
    def queryset(self):
        return super(PublishedManager, self).queryset().filter(
            status='published'
        )


# post models
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(
        upload_to='feature_img/%Y/%m/%d', blank=True, null=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts")
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="Draft")
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog2:post_detail', args=[self.slug])

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.body

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

blog2/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-control', 'placeholder': 'Commentaire....', 
                'style': 'max-width: 100%;',
            })
        }

    # Overriding default from settings and adding bootstrap class
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {'placeholder': 'Enter name', 'class':'form-control',}
        self.fields['email'].widget.attrs = {'placeholder': 'Enter email', 'class':'form-control'}
        

blog2/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count, Q
from blog2.forms import CommentForm
from .models import Comment, Post


def about(request):
    return render(request, 'blog2/about.html')


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    paginator = Paginator(posts, 12)
    page = request.GET.get('page')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    # Search
    query = request.GET.get('q')
    if query:
        posts = Post.published.filter(
            Q(title__icontains=query) | Q(tags__name__icontains=query))

    context = {
        'posts': posts,
        'page': page,
        'tag': tag,
    }
    return render(request, 'blog2/post_list.html', context)


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment post to the comment
            new_comment.save()
            # redirect to same page and focus on that  comment
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:6]
    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog2/post_detail.html', context)


def reply_page(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)
            reply.post = Post(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()

            return redirect(post_url+'#'+str(reply.id))

    return redirect("/")

blog2/templates/blog2/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <article class="container mt-5">
        
            <div class="mt-3">
                <h1 class="text-center mb-3 fw-bold">À propos de Diarra Moustapha</h1>
                <img src="{% static 'img/toph.png' %}" class="mx-auto d-block" height="400px" width="400px" alt="title">
                <p class="mt-3">
                    Bonjour, je suis Diarra Moustapha, diplomé en génie informatique, fondateur de Planète Code. J'aide
                    les gens à apprendre la programmation informatique de maniere simple et pratique. J'écris du code en
                    Python, Java, C++, HTML/CSS, Javascript et Kotlin. Et mon langage de programmation préféré de tous les
                    temps est Python. J'ai creé ce site Web pour partager mes connaissances et vous aider à devenir un
                    meilleur programmeur.
                </p>
                <h2>Mon histoire de carrière</h2>
                <p>
                    L'histoire commence en 2018. Après avoir en mon baccalauréat scientifique et faire 2 années d'etude
                    universitaire en mathematique et informatique.
                    Je decide de venir en Russie pour continuer mes etudes et c'est de là qu'est venue ma passion pour l'
                    informatique surtout pour la programmation et je decide de faire carrière.
                </p>
                <p>
                    Ma première année à l'université en Russie, je découvre Python et je tombe amoureux de ce langage.
                    Après avoir réalisé plusieurs projets en python, je décide d'etre polyvalent. J'ai appris
                    HTML, CSS Javascript, PHP, Java et Kotlin, et créé de nombreuses applications web.
                </p>
                <p>
                    J'ai commencé mon apprentissage Python avec le livre de Gerald Swimmen "Apprendre Python" et
                    suivre des tutoriels sur internet. Mais je lis beaucoup dont j'ai vite appréhendé les concepts. J'ai appris
                    python à fond. Je ne sais pas pourquoi, mais j'aime beaucoup plus coder en python et Java que les
                    autres langages.
                </p>
                <p>
                    J'ai utilisé des modules et frameworks Python comme Tkinter, Turtle, Django, Flask, Numpy,
                    Pandas, Matplotlib, Seaborn, Scikit-Learn, TensorFlow, Keras, etc. pour construire plusieurs
                    projets. J'ai créé un site pour permettre aux touristes de visiter des lieux et de faire
                    des reservation du genre de Booking. En 2021, j'ai obtenus mon bachelor en génie Logiciel.
                    À l'heure où j'écris ces lignes, je suis en master 1 en génie informatique.
                </p>
                <h2>Certifications et réalisations</h2>
                <p>
                    J'ai été reconnu pour des choses incroyables et des choses très idiotes au fil des ans.
                    Mais voici quelques certifications dont je suis assez fier !
                    <ul>
                        <li><a href="https://openclassrooms.com/fr/course-certificates/8665961403">Démarrer votre projet avec Python</a> </li>
                    </ul>
                </p>
                <h2>Détails du contact</h2>
                <p>
                    Si vous souhaitez me contacter, n'hésiter pas à écrire un email à <a href="mailto:diarra.msa@gmail.com">diarra.msa1@gmail.com</a>.
                </p>
                <p>
                    Vous pouvez aussi me trouver sur <a href="https://github.com/DinoRu">Github</a>, qui n'est pas
                    très actif ces jours-ci.
                </p>
                <h2>Mes Series</h2>
                <ul>
                    <li>Game of Trone</li>
                    <li>History 101</li>
                    <li>Power</li>
                    <li>#Philo</li>
                    <li>Society</li>
                </ul>
            </div>
    </article>
{% endblock %}

blog2/templates/blog2/comment.html
<div class="border-0 border-start border-2 border-info ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{comment.body}}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'blog2:reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">
                {{comment_form.as_p}}
                <div>
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'blog2/comment.html' with comment=comment %}
    {% endfor %}
</div>

blog2/templates/blog2/comments.html
<div class="border-0 border-start border-2 border-info ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{comment.body}}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'blog2:reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">
                {{comment_form.as_p}}
                <div>
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'blog2/comments.html' with comment=comment %}
    {% endfor %}
</div>

blog2/templates/blog2/pagination.html
<nav class="justify-content-center">
    <ul class="pagination mt-4 mb-0 justify-content-center">
      {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% else %}
        <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="active page-item"><span class="page-link">{{ i }}</span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a></li>
      {% else %}
        <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
      {% endif %}
    </ul>
</nav>

blog2/templates/blog2/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}-{{ post.title }}{% endblock %}

{% block content %}


    <article class="container mt-5">
        <figure>
            <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="rounded" alt="{{post.title}}" height="260px" width="100%">
        </figure>
        <div class="mt-3">
            <h1 class="fw-bolder">{{ post.title }}</h1>
            <p class="text-muted">
                Published {{ post.publish.date }} by <strong>{{post.author}}</strong>
            </p>
        </div>
        <div class="article-body">
            {{ post.body|safe|linebreaks }}
        </div>
        <p>
            <strong>Tags:</strong>
            {% for tag in post.tags.all %}
                <a href="{% url 'blog2:post_tag' tag.slug %}" class="link-light text-decoration-none badge bg-secondary">
                    {{ tag.name }}
                </a>
            {% endfor %}
        </p>
        <hr/>
        <br>
        {% include 'comments.html' with url=post.pk %}
        <hr>
        <hr />
        <div class="my-3">
            <h3>Similar Posts</h3>
        </div>
        <div class="row">
            {% for post in similar_posts %}
            <div class="col-md-6 col-sm-6 col-lg-4 mb-3">
                <div class="card border-0">
                    <div class="ratio ratio-16x9">
                        <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="rounded featured-image-list" alt="{{post.title}}">
                    </div>
                    <div class="card-body p-0 m-0 mt-2">
                        <h2 class="card-title h6 my-0 py-0">
                            <a href="{{ post.get_absolute_url }}" class="text-center text-decoration-none text-dark h4 fw-bolder">{{ post.title }}</a>
                        </h2>
                        <p class="card-text">
                            <small class="text-muted">
                                <span>{{post.publish.date}} by
                                    <b>{{ post.author }}</b></span>
                                <!-- <a href="" class="badge badge-light text-muted">{{post.tags.all|join:" "}}</a> -->
                            </small>
                        </p>
                        <!-- <p>{{post.body|truncatechars:100|linebreaks}}</p> -->
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-muted">There is no similar post yet</p>
            {% endfor %}
        </div>
    </article>


{% endblock %}

blog2/templates/blog2/post_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}blog2-list{% endblock %}

{% block content %}
    
<div class="container">
  <div class="row gy-4">
    {% if tag %}
      <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    <h2 class="text-center text-uppercase h1 mt-5 border-bottom fw-bolder">Framework web Django</h2>
    {% for post in posts %}
      <div class="col-12 col-md-6 col-lg-4 mt-5">
        <div class="card border-0">
          <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="rounded" href="{{ post.get_absolute_url }}">
          <div class="card-body">
            <h3 class="card-title text-dark fw-bolder"><a href="{{ post.get_absolute_url }}" class="text-decoration-none text-dark">{{ post.title}}</a></h3>
            <p class="text-muted"><small>{{post.created.date}} · {{ post.author }}</small></p>
          </div>
        </div>
      </div>
    {% endfor %}
    {% include "blog2/pagination.html" with page=posts %}
  </div>
</div>

    
{% endblock %}